sudo: required
services:
  - docker

before_install:
  - docker build -t drakemage47/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true drakemage47/docker-react npm run test

Deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Docker-react-env"
  bucket_name: "elasticbeanstalk-us-east-1-085872799185"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
